from __future__ import annotations

import json
import random
from pathlib import Path
from typing import Sequence

import numpy as np
import torch
from PIL import Image, ImageEnhance, ImageFilter
from torch.utils.data import Dataset


IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".tif", ".tiff", ".bmp"}
IMAGENET_MEAN = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
IMAGENET_STD = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)


def _relative_key(path: Path, root: Path) -> str:
    return path.relative_to(root).with_suffix("").as_posix()


def indexed_files(root: str | Path) -> dict[str, Path]:
    """Index supported images by relative path without the extension."""
    root = Path(root)
    if not root.is_dir():
        raise FileNotFoundError(f"Directory not found: {root}")
    result: dict[str, Path] = {}
    for path in sorted(root.rglob("*")):
        if path.is_file() and path.suffix.lower() in IMAGE_SUFFIXES:
            key = _relative_key(path, root)
            if key in result:
                raise ValueError(f"Duplicate relative key {key!r} in {root}")
            result[key] = path
    return result


def paired_samples(image_root: str | Path, mask_root: str | Path) -> list[tuple[Path, Path]]:
    images = indexed_files(image_root)
    masks = indexed_files(mask_root)
    common = sorted(images.keys() & masks.keys())
    if not common:
        raise ValueError("No image/mask pairs found by matching relative paths")
    missing_masks = sorted(images.keys() - masks.keys())
    missing_images = sorted(masks.keys() - images.keys())
    if missing_masks or missing_images:
        raise ValueError(
            f"Unpaired files: missing_masks={len(missing_masks)}, missing_images={len(missing_images)}"
        )
    return [(images[key], masks[key]) for key in common]


def split_samples(
    samples: list[tuple[Path, Path]], val_fraction: float, seed: int
) -> tuple[list[tuple[Path, Path]], list[tuple[Path, Path]]]:
    """Deterministic fallback split; formal runs should use a generated split file."""
    if len(samples) < 2:
        raise ValueError("At least two paired samples are required for train/validation split")
    if not 0 < val_fraction < 1:
        raise ValueError("val_fraction must be between 0 and 1")
    shuffled = samples.copy()
    random.Random(seed).shuffle(shuffled)
    val_size = max(1, min(len(shuffled) - 1, round(len(shuffled) * val_fraction)))
    return shuffled[val_size:], shuffled[:val_size]


def split_samples_from_file(
    samples: Sequence[tuple[Path, Path]], split_path: str | Path
) -> tuple[list[tuple[Path, Path]], list[tuple[Path, Path]]]:
    """Apply train/val keys generated by tools/profile_dataset.py."""
    payload = json.loads(Path(split_path).read_text(encoding="utf-8"))
    train_keys = set(payload["train"])
    val_keys = set(payload["val"])
    if train_keys & val_keys:
        raise ValueError("Split file has overlapping train and validation keys")
    by_key = {image.stem: (image, mask) for image, mask in samples}
    if len(by_key) != len(samples):
        raise ValueError("Split files currently require unique filename stems")
    missing = (train_keys | val_keys) - set(by_key)
    if missing:
        raise ValueError(f"Split references {len(missing)} missing samples")
    unused = set(by_key) - (train_keys | val_keys)
    if unused:
        raise ValueError(f"Split omits {len(unused)} available samples")
    return [by_key[key] for key in sorted(train_keys)], [by_key[key] for key in sorted(val_keys)]


class SegmentationDataset(Dataset):
    def __init__(
        self,
        samples: Sequence[tuple[Path, Path]],
        crop_size: int,
        training: bool,
        num_classes: int = 9,
        scale_range: tuple[float, float] = (0.75, 1.5),
        color_jitter: float = 0.2,
        rare_class_ids: Sequence[int] = (5, 7, 8),
        rare_crop_probability: float = 0.5,
    ) -> None:
        self.samples = list(samples)
        self.crop_size = crop_size
        self.training = training
        self.num_classes = num_classes
        self.scale_range = scale_range
        self.color_jitter = color_jitter
        self.rare_class_ids = tuple(rare_class_ids)
        self.rare_crop_probability = rare_crop_probability

    def __len__(self) -> int:
        return len(self.samples)

    def _resize_for_training(
        self, image: Image.Image, mask: Image.Image
    ) -> tuple[Image.Image, Image.Image]:
        scale = random.uniform(*self.scale_range)
        target_w = max(self.crop_size, round(image.width * scale))
        target_h = max(self.crop_size, round(image.height * scale))
        image = image.resize((target_w, target_h), Image.Resampling.BILINEAR)
        mask = mask.resize((target_w, target_h), Image.Resampling.NEAREST)
        return image, mask

    def _random_crop(
        self, image: Image.Image, mask: Image.Image
    ) -> tuple[Image.Image, Image.Image]:
        width, height = image.size
        attempts = 8 if random.random() < self.rare_crop_probability else 1
        selected_box = None
        for _ in range(attempts):
            left = random.randint(0, width - self.crop_size)
            top = random.randint(0, height - self.crop_size)
            box = (left, top, left + self.crop_size, top + self.crop_size)
            selected_box = box
            if attempts == 1:
                break
            crop = np.asarray(mask.crop(box))
            if np.isin(crop, self.rare_class_ids).mean() >= 0.005:
                break
        assert selected_box is not None
        return image.crop(selected_box), mask.crop(selected_box)

    def _photometric(self, image: Image.Image) -> Image.Image:
        jitter = self.color_jitter
        operations = [
            lambda value: ImageEnhance.Brightness(value).enhance(random.uniform(1 - jitter, 1 + jitter)),
            lambda value: ImageEnhance.Contrast(value).enhance(random.uniform(1 - jitter, 1 + jitter)),
            lambda value: ImageEnhance.Color(value).enhance(random.uniform(1 - jitter, 1 + jitter)),
        ]
        random.shuffle(operations)
        for operation in operations:
            image = operation(image)
        if random.random() < 0.15:
            image = image.filter(ImageFilter.GaussianBlur(radius=random.uniform(0.1, 1.2)))
        return image

    def __getitem__(self, index: int) -> dict[str, torch.Tensor | str]:
        image_path, mask_path = self.samples[index]
        with Image.open(image_path) as loaded:
            image = loaded.convert("RGB")
        with Image.open(mask_path) as loaded:
            mask = loaded.convert("L")
        if image.size != mask.size:
            raise ValueError(f"Size mismatch for {image_path.name}: {image.size} vs {mask.size}")

        if self.training:
            image, mask = self._resize_for_training(image, mask)
            image, mask = self._random_crop(image, mask)
            if random.random() < 0.5:
                image = image.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
                mask = mask.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
            if random.random() < 0.5:
                image = image.transpose(Image.Transpose.FLIP_TOP_BOTTOM)
                mask = mask.transpose(Image.Transpose.FLIP_TOP_BOTTOM)
            rotations = random.randint(0, 3)
            if rotations:
                operation = {
                    1: Image.Transpose.ROTATE_90,
                    2: Image.Transpose.ROTATE_180,
                    3: Image.Transpose.ROTATE_270,
                }[rotations]
                image = image.transpose(operation)
                mask = mask.transpose(operation)
            image = self._photometric(image)

        image_array = np.asarray(image, dtype=np.float32).transpose(2, 0, 1) / 255.0
        mask_array = np.asarray(mask, dtype=np.int64)
        invalid = (mask_array < 0) | (mask_array >= self.num_classes)
        if invalid.any():
            values = np.unique(mask_array[invalid]).tolist()
            raise ValueError(f"Unexpected class IDs in {mask_path}: {values}")

        pixels = (torch.from_numpy(image_array) - IMAGENET_MEAN) / IMAGENET_STD
        return {
            "pixel_values": pixels,
            "labels": torch.from_numpy(mask_array.copy()).long(),
            "name": image_path.stem,
        }
